# Generated by Django 2.1.2 on 2018-11-03 22:44

import core.utils
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='APIKey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('token', models.CharField(blank=True, default=core.utils.gen_token, max_length=256, unique=True)),
                ('active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='analytics_minimal_apikey_creator_related', related_query_name='analytics_minimal_apikeys_creator', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PageView',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('token', models.CharField(blank=True, default=core.utils.gen_token, max_length=256, unique=True)),
                ('event_id', models.CharField(max_length=256)),
                ('event_name', models.CharField(max_length=256)),
                ('previous_event_id', models.CharField(blank=True, max_length=256, null=True)),
                ('hostname', models.CharField(max_length=256)),
                ('path', models.CharField(max_length=256)),
                ('browser', models.CharField(blank=True, max_length=256, null=True)),
                ('duration', models.DurationField(blank=True, null=True)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('is_bounce', models.BooleanField(default=True)),
                ('is_new_session', models.BooleanField(default=False)),
                ('is_new_user', models.BooleanField(default=False)),
                ('page_load_time', models.FloatField(blank=True, null=True)),
                ('referrer', models.CharField(blank=True, max_length=256, null=True)),
                ('screen_height', models.IntegerField(blank=True, null=True)),
                ('screen_width', models.IntegerField(blank=True, null=True)),
                ('raw_request', models.TextField(blank=True, null=True)),
                ('api_key', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='analytics_minimal.APIKey')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('token', models.CharField(blank=True, default=core.utils.gen_token, max_length=256, unique=True)),
                ('hostname', models.CharField(max_length=256)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='analytics_minimal_site_creator_related', related_query_name='analytics_minimal_sites_creator', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='analytics_minimal_site_updater_related', related_query_name='analytics_minimal_sites_updater', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='pageview',
            name='site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='analytics_minimal.Site'),
        ),
        migrations.AddField(
            model_name='apikey',
            name='site',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='analytics_minimal.Site'),
        ),
        migrations.AddField(
            model_name='apikey',
            name='updated_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='analytics_minimal_apikey_updater_related', related_query_name='analytics_minimal_apikeys_updater', to=settings.AUTH_USER_MODEL),
        ),
    ]
