# Generated by Django 2.1.2 on 2018-11-18 17:46

import core.utils
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('analytics_minimal', '0002_auto_20181108_0223'),
    ]

    operations = [
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('token', models.CharField(blank=True, default=core.utils.gen_token, max_length=256, unique=True)),
                ('active', models.BooleanField(default=True)),
                ('duration', models.DurationField(blank=True, null=True)),
                ('first_session', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Visitor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('token', models.CharField(blank=True, default=core.utils.gen_token, max_length=256, unique=True)),
                ('site', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='analytics_minimal.Site')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='pageview',
            name='next_event_id',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='pageview',
            name='browser',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pageview',
            name='hostname',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='pageview',
            name='path',
            field=models.TextField(),
        ),
        migrations.AddField(
            model_name='session',
            name='first_page_view',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='first_page_view', to='analytics_minimal.PageView'),
        ),
        migrations.AddField(
            model_name='session',
            name='last_page_view',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='last_page_view', to='analytics_minimal.PageView'),
        ),
        migrations.AddField(
            model_name='session',
            name='site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='analytics_minimal.Site'),
        ),
        migrations.AddField(
            model_name='session',
            name='visitor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='analytics_minimal.Visitor'),
        ),
        migrations.AddField(
            model_name='pageview',
            name='session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='analytics_minimal.Session'),
        ),
    ]
